name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # - name: Install dependencies
      #   run: npm 

      # - name: Lint
      #   run: npm run lint

      # - name: Type check
      #   run: npm run typecheck

      # - name: Build
      #   run: npm run build

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TENCENT_HOST }}
          username: ${{ secrets.TENCENT_USER }}
          key: ${{ secrets.TENCENT_SSH_KEY }}
          script: |
            cd /data/nginx/webclone/
            git pull 
            npm install
            npm run build
            pm2 restart websiteclone
